{% set version = "1.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-superpc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/superpc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/superpc/superpc_{{ version }}.tar.gz
  sha256: cbed883e91a124becb147b735f10b80bd25c631eba9ed139c00070ae9dc2c858

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-survival
  run:
    - r-base
    - r-survival

test:
  commands:
    - $R -e "library('superpc')"           # [not win]
    - "\"%R%\" -e \"library('superpc')\""  # [win]

about:
  home: http://www-stat.stanford.edu/~tibs/superpc, https://github.com/jedazard/superpc
  license: GPL-3.0-or-later
  summary: Supervised principal components for regression and survival analsysis. Especially useful for high-dimnesional data, including microarray data.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
